spring:
  application:
    name: jnu-locker

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      base-path: ${MANAGEMENT_BASE_PATH}
      exposure:
        include:
          - health
          - prometheus
    access:
      default: none
  endpoint:
    health:
      access: unrestricted
    prometheus:
      access: unrestricted

logging:
  level:
    root: ${LOGGING_LEVEL}  # TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF

  file:
    name: ${LOGGING_DIR}/${LOGGING_FILE}

  logback:
    rollingpolicy:
      max-history: 30       # default: 7
      max-file-size: 10MB   # default: 10MB
      total-size-cap: 5GB   # default: 제한 없음
      file-name-pattern: ${LOGGING_DIR}/${LOGGING_FILE_NAME_PATTERN} # 압축해서 보관 -> 디스크 절약

springdoc:
  api-docs:
    path: /api-docs # default: /v3/api-docs

# p6spy 로깅 활성화 (JDBC 이벤트 로깅)
decorator:
  datasource:
    p6spy:
      enable-logging: true

custom:
  jwt:
    access-secret-key: ${JWT_ACCESS_SECRET_KEY:dGVzdC1zZWNyZXQta2V5LXRlc3Qtc2VjcmV0LWtleS10ZXN0LXNlY3JldC1rZXktdGVzdC1zZWNyZXQta2V5}
    refresh-secret-key: ${JWT_REFRESH_SECRET_KEY:dGVzdC1yZWZyZXNoLXNlY3JldC1rZXktdGVzdC1yZWZyZXNoLXNlY3JldC1rZXktdGVzdC1yZWZyZXNoLXNlY3JldC1rZXktdGVzdC1yZWZyZXNo}
    access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME:1}
    refresh-token-expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME:86400}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

---
spring:
  config:
    activate:
      on-profile: dev

  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: prod

  sql:
    init:
      mode: never

# 프로덕션 환경에서는 p6spy 로깅을 비활성화
decorator:
  datasource:
    p6spy:
      enable-logging: false

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:tc:mysql:8.0:///test-database
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  sql:
    init:
      mode: never

logging:
  level:
    p6spy: info
    org.springframework:
      transaction.interceptor: trace
