server {
  listen 80;
  server_name api.dev.jnu-locker.site;

  access_log /home/jnu-locker/log/access.log;
  error_log /home/jnu-locker/log/error.log;

  location / {
    proxy_pass http://was:8080; # docker compose에서 서비스 이름인 was로 프록시
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /swagger-ui {
    proxy_pass http://was:8080;
  }

  location /prometheus/ {
    proxy_pass http://prometheus:9090/;
    proxy_set_header Host $host;
    proxy_redirect / /prometheus/;
  }

  location /grafana/ {
    proxy_pass http://grafana:3000/;
    rewrite ^/grafana/?(.*) /$1 break;
    proxy_set_header Host $host;
  }
}
