name: image build and push

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_REPO:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: 이미지 빌드하기

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Jib
        id: build-image
        env:
          PROFILE: ${{ github.ref_name }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          IMAGE_TAG: ${{ github.ref }}

        run: |
          echo "PROFILE=$PROFILE" &&
          echo "DOCKER_USERNAME=$DOCKER_USERNAME" &&
          ./gradlew jib
